import React, { useEffect, useState } from "react";
import {
  Box,
  Button,
  CircularProgress,
  IconButton,
  Modal,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  TextField,
} from "@mui/material";
import styles from "./StripeProductsDashboard.module.css";
import ProductUpsertForm from "./ProductUpsertForm";
import BorderColorIcon from "@mui/icons-material/BorderColor";
import {
  AddCircleOutline,
  Cancel,
  CheckCircleOutline,
} from "@mui/icons-material";
import PriceCreationForm from "./PriceCreationForm";
import { useForm, Controller } from "react-hook-form";
import { t } from "i18next";
import ConfirmationDialog from "../../ConfirmationDialog";

const StripeProductsDashboardComponent = () => {
  const [stripeProduct, setStripeProduct] = useState(null);
  const [stripePrices, setStripePrices] = useState([]);
  const [isLoadingProduct, setIsLoadingProduct] = useState(true);
  const [isLoadingPrice, setIsLoadingPrice] = useState(true);
  const [isPriceDialogOpened, setIsPriceDialogOpened] = useState(false);
  const [isProductDialogOpened, setIsProductDialogOpened] = useState(false);
  const [merchantAddressData, setMerchantAddressData] = useState(undefined);
  const [merchantAddressSubmitted, setMerchantAddressSubmitted] =
    useState(false);
  const {
    control,
    handleSubmit,
    formState: { errors },
  } = useForm();
  const fetchWithCredentials = (url, options) => {
    return fetch(url, { ...options, credentials: "include" });
  };
  useEffect(() => {
    const fetchData = async () => {
      try {
        // HACK: Add condition to add merchant's address before allowing to edit anything else
        debugger;
        const merchantAddressResponse = await fetchWithCredentials(
          `https://${process.env.REACT_APP_API_ADDRESS}/Merchant`
        );
        const merchantAddressData =
          merchantAddressResponse.status === 200
            ? await merchantAddressResponse.json()
            : undefined;

        setMerchantAddressData(merchantAddressData);

        const productResponse = await fetchWithCredentials(
          `https://${process.env.REACT_APP_API_ADDRESS}/StripeProducts/FetchSubscriptionPlan`
        );
        const productData =
          productResponse.status === 200
            ? await productResponse.json()
            : undefined;
        if (productData) {
          setStripeProduct(productData);
          await reloadPrices(productData.id);
        } else {
        }

        setIsLoadingProduct(false);
      } catch (error) {
        console.error("Error fetching Stripe data:", error);
        setIsLoadingProduct(false);
      }
    };
    setIsLoadingProduct(true);
    fetchData();
  }, [isProductDialogOpened, isPriceDialogOpened]);

  const reloadPrices = async (productId) => {
    setIsLoadingPrice(true);
    const pricesResponse = await fetchWithCredentials(
      `https://${process.env.REACT_APP_API_ADDRESS}/StripeProducts/GetAllPrices?productId=${productId}`
    );
    const pricesList =
      pricesResponse.status === 200 ? await pricesResponse.json() : undefined;
    if (pricesList) {
      setStripePrices(pricesList);
    }
    setIsLoadingPrice(false);
  };

  const openEditDialog = () => {
    setIsProductDialogOpened(true);
  };

  const openPriceDialog = () => {
    setIsPriceDialogOpened(true);
  };

  const toggleActivation = async (priceId) => {
    setIsLoadingProduct(true);
    await fetchWithCredentials(
      `https://${process.env.REACT_APP_API_ADDRESS}/StripeProducts/TogglePriceState?priceId=${priceId}`,
      {
        method: "PUT",
      }
    );
    await reloadPrices(stripeProduct.id);
    setIsLoadingProduct(false);
  };

  const onSubmit = async (submitFormData) => {
    if (
      submitFormData.appartmentNo === "" ||
      isNaN(submitFormData.appartmentNo)
    ) {
      submitFormData.appartmentNo = null;
    } else {
      submitFormData.appartmentNo = parseInt(submitFormData.appartmentNo, 10);
    }
    const merchantAddressResponse = await fetch(
      `https://${process.env.REACT_APP_API_ADDRESS}/Merchant`,
      {
        method: "PUT",
        body: JSON.stringify(submitFormData),
        headers: [["content-type", "application/json"]],
        credentials: "include",
      }
    );
    if (merchantAddressResponse.status === 200) {
      const wasSubmittedSuccesfully =
        (await merchantAddressResponse.json()) === 1;
      if (wasSubmittedSuccesfully) setMerchantAddressSubmitted(true);
    }
  };

  const getMerchantAddressContent = () => {
    if (isLoadingPrice) {
      return <></>;
    } else {
      return (
        <>
          <h4>Review your company's address:</h4>
          <p>
            The address below will appear on the invoices generated by the
            system as merchant
          </p>
          <form onSubmit={handleSubmit(onSubmit)}>
            <div className={styles.container}>
              <div className={styles.row}>
                <div className={styles.field}>
                  <Controller
                    name="companyName"
                    control={control}
                    defaultValue={
                      merchantAddressData ? merchantAddressData.companyName : ""
                    }
                    rules={{
                      required: "Company name is required",
                      minLength: {
                        value: 3,
                        message:
                          "Company name must be at least 3 characters long",
                      },
                    }}
                    render={({ field }) => (
                      <TextField
                        {...field}
                        label="Company name"
                        error={!!errors.companyName}
                        helperText={
                          errors.companyName ? errors.companyName.message : ""
                        }
                      />
                    )}
                  />
                </div>
                <div className={styles.field}>
                  <Controller
                    name="companyTaxId"
                    control={control}
                    defaultValue={
                      merchantAddressData
                        ? merchantAddressData.companyTaxId
                        : ""
                    }
                    rules={{
                      required: "Tax id is required",
                      minLength: {
                        value: 3,
                        message: "",
                      },
                      pattern: {
                        value: /^[A-Za-z0-9\s]+$/,
                        message: "Invalid last name",
                      },
                    }}
                    render={({ field }) => (
                      <TextField
                        {...field}
                        label="Company Tax Id"
                        error={!!errors.companyTaxId}
                        helperText={
                          errors.companyTaxId ? errors.companyTaxId.message : ""
                        }
                      />
                    )}
                  />
                </div>
              </div>
              <div className={styles.row}>
                <div className={styles.field}>
                  <Controller
                    name="street"
                    control={control}
                    defaultValue={
                      merchantAddressData ? merchantAddressData.street : ""
                    }
                    rules={{
                      required: "Street is required",
                      minLength: {
                        value: 3,
                        message: "Street must be at least 3 characters long",
                      },
                      pattern: {
                        value: /^[A-Za-z0-9\s]+$/,
                        message: "Invalid street name",
                      },
                    }}
                    render={({ field }) => (
                      <TextField
                        {...field}
                        label="Street"
                        error={!!errors.street}
                        helperText={errors.street ? errors.street.message : ""}
                      />
                    )}
                  />
                </div>
                <div className={styles.field}>
                  <Controller
                    name="houseNo"
                    defaultValue={
                      merchantAddressData ? merchantAddressData.houseNo : ""
                    }
                    control={control}
                    rules={{
                      required: "House number is required",
                      pattern: {
                        value: /^[0-9]+[A-Za-z]?\/?[0-9]*[A-Za-z]?$/,
                        message: "Invalid house number",
                      },
                    }}
                    render={({ field }) => (
                      <TextField
                        {...field}
                        label="House number"
                        error={!!errors.houseNo}
                        helperText={
                          errors.houseNo ? errors.houseNo.message : ""
                        }
                      />
                    )}
                  />
                </div>
                <div className={styles.field}>
                  <Controller
                    name="appartmentNo"
                    control={control}
                    defaultValue={
                      merchantAddressData
                        ? merchantAddressData.appartmentNo
                        : ""
                    }
                    rules={{
                      min: {
                        value: 1,
                        message: "Apartment number must be greater than zero",
                      },
                      pattern: {
                        value: /^(?!0+$)\d+$/,
                        message:
                          "Invalid apartment number. Only numbers greater than zero are allowed.",
                      },
                    }}
                    render={({ field }) => (
                      <TextField
                        {...field}
                        label="Appartment number"
                        error={!!errors.appartmentNo}
                        type="number"
                        InputProps={{ inputProps: { min: 1 } }}
                        helperText={
                          errors.appartmentNo ? errors.appartmentNo.message : ""
                        }
                      />
                    )}
                  />
                </div>
              </div>
              <div className={styles.row}>
                <div className={styles.field}>
                  <Controller
                    name="postCode"
                    control={control}
                    defaultValue={
                      merchantAddressData ? merchantAddressData.postCode : ""
                    }
                    rules={{
                      required: "Post code is required",
                      pattern: {
                        value: /^\d{2}-\d{3}$/,
                        message: "Post code must be in the format XX-XXX",
                      },
                    }}
                    render={({ field }) => (
                      <TextField
                        {...field}
                        label="Post code"
                        error={!!errors.postCode}
                        helperText={
                          errors.postCode ? errors.postCode.message : ""
                        }
                      />
                    )}
                  />
                </div>
                <div className={styles.field}>
                  <Controller
                    name="city"
                    control={control}
                    defaultValue={
                      merchantAddressData ? merchantAddressData.city : ""
                    }
                    rules={{
                      required: "City is required",
                      minLength: {
                        value: 3,
                        message: "City name must be at least 3 characters long",
                      },
                      pattern: {
                        value: /^[A-Za-z\s]{3,}$/,
                        message: "Invalid city name",
                      },
                    }}
                    render={({ field }) => (
                      <TextField
                        {...field}
                        label="City"
                        error={!!errors.city}
                        helperText={errors.city ? errors.city.message : ""}
                      />
                    )}
                  />
                </div>
                <div className={styles.field}>
                  <Controller
                    name="Country"
                    control={control}
                    rules={{ required: "Country is required" }}
                    defaultValue="Polska"
                    render={({ field }) => (
                      <TextField
                        {...field}
                        disabled={true}
                        label="Country"
                        error={!!errors.country}
                        helperText={
                          errors.country ? errors.country.message : ""
                        }
                      />
                    )}
                  />
                </div>
              </div>
            </div>
            <Button type="submit">{t("SaveCompanyData")}</Button>
          </form>
        </>
      );
    }
  };

  const getPricesContent = () => {
    if (isLoadingPrice)
      return (
        <div className={styles.container}>
          <CircularProgress size={100} />
        </div>
      );
    else if (stripePrices)
      return (
        <Table>
          <TableHead>
            <TableRow>
              <TableCell>ID</TableCell>
              <TableCell>{t("Price")}</TableCell>
              <TableCell>{t("State")}</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {stripePrices.map((price) => (
              <TableRow key={price.id}>
                <TableCell>{price.id}</TableCell>
                <TableCell>
                  {`${price.currency.toUpperCase()} ${
                    price.unitAmount / 100
                  },-`}
                </TableCell>
                <TableCell>
                  {price.isActive ? (
                    <>
                      <CheckCircleOutline className="text-green" />{" "}
                      <Button onClick={() => toggleActivation(price.id)}>
                        {t("Deactivate")}
                      </Button>
                    </>
                  ) : (
                    <>
                      <Cancel className="text-red" />
                      <Button onClick={() => toggleActivation(price.id)}>
                        {t("Activate")}
                      </Button>
                    </>
                  )}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      );
    else return <h4>{t("NoPricesYet")}</h4>;
  };

  return (
    <div className={styles.container}>
      {getMerchantAddressContent()}
      <hr className={styles.divider} />
      {stripeProduct ? (
        <div>
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-auto">
                <h4>{stripeProduct.name}</h4>
              </div>
              <div className="col-auto">
                <IconButton onClick={openEditDialog}>
                  <BorderColorIcon className={styles.editButton} />
                </IconButton>
              </div>
            </div>
          </div>
          <div className={styles.table}>
            <IconButton color="primary" onClick={openPriceDialog}>
              <AddCircleOutline style={{ fontSize: "24px" }} />
            </IconButton>
            {t("AddANewPrice")}
          </div>
          {getPricesContent()}
        </div>
      ) : (
        <div className={styles.container}>
          {isLoadingProduct ? (
            <h1>
              <CircularProgress />
            </h1>
          ) : (
            <>
              <h3>{t("SubscriptionPlan")}</h3>
              <p>{t("CreateYourFirstPlan")}</p>
              {!isProductDialogOpened && (
                <IconButton
                  color="primary"
                  aria-label="add new product"
                  onClick={() => setIsProductDialogOpened(true)}
                >
                  <AddCircleOutline style={{ fontSize: "48px" }} />
                </IconButton>
              )}
            </>
          )}
        </div>
      )}
      <ProductUpsertForm
        stripeProduct={stripeProduct}
        setStripeProduct={(data) => {
          setStripeProduct(data);
        }}
        isDialogOpened={isProductDialogOpened}
        setIsDialogOpened={setIsProductDialogOpened}
      />
      <PriceCreationForm
        isPriceDialogOpened={isPriceDialogOpened}
        setIsPriceDialogOpened={setIsPriceDialogOpened}
        stripeProduct={stripeProduct}
      />
      <ConfirmationDialog
        title={t("Success")}
        message={t("MerchantAddressUpserted")}
        open={merchantAddressSubmitted}
        hasCancelOption={false}
        onConfirm={() => {
          setMerchantAddressSubmitted(false);
        }}
      ></ConfirmationDialog>
    </div>
  );
};

export default StripeProductsDashboardComponent;
